const actionType = {

    SEARCH_MUTE_ALL : 'SEARCH_MUTE_ALL' ,
    SEARCH_GET_CURRENT_WETHER : 'SEARCH_GET_CURRENT_WETHER',
    SEARCH_GET_CURRENT_WETHER_SUCCESS : 'SEARCH_GET_CURRENT_WETHER_SUCCESS',
    SEARCH_GET_CURRENT_WETHER_FAILURE : 'SEARCH_GET_CURRENT_WETHER_FAILURE',
   
}

export default actionType