const actionType = {

    HOME_SET_LOCATION_VALUES : 'HOME_SET_LOCATION_VALUES',
    HOME_GET_CURRENT_WETHER : 'HOME_GET_CURRENT_WETHER',
    HOME_GET_CURRENT_WETHER_SUCCESS : 'HOME_GET_CURRENT_WETHER_SUCCESS',
    HOME_GET_CURRENT_WETHER_FAILURE : 'HOME_GET_CURRENT_WETHER_FAILURE'
   
}

export default actionType